# Generated by Django 4.0.3 on 2022-04-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_guitar_email_alter_guitar_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
