# Generated by Django 4.0.3 on 2022-04-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_guitar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
